### PR TITLE
Upgrade Go2Sky to 0.5.0

### PR DESCRIPTION
**Pull request by arugal**
### Issues associated with this PR

Your PR should present related issues you want to solve.

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### NOTICE

go2sky no longer needs to provide a special branch for MOSN because MOSN has upgraded the GRPC version.

### CODE REVIEW

**Comment by arugal** [comment]
###  Screenshots
image
image

**Comment by arugal** [comment]
@rootsongjc @nejisama   @taoyuanyuan  We are separating the go2sky kernel from the plugin https://github.com/SkyAPM/go2sky/pull/68. Please merge after this :)

**Comment by arugal** [comment]
@cch123 Please review :)

**Comment by cch123** [comment]
@arugal , I'll check this pr next week~

**Comment by cch123** [comment]
LGTM

**Pull request merged**
