### PR TITLE
deps: updates wazero to 1.2.1 

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This updates [wazero](https://wazero.io/) to [1.2.1](https://github.com/tetratelabs/wazero/releases/tag/v1.2.1) which improves performance and support for non-blocking I/O.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

```bash
$ go test -run='^$' -tags wasmer -bench '^Benchmark_.*' ./test/integrate/proxywasm -count=6 > old.txt
$ go test -run='^$' -tags wasmer -bench '^Benchmark_.*' ./test/integrate/proxywasm -count=6 > new.txt
goos: darwin
goarch: arm64
pkg: mosn.io/mosn/test/integrate/proxywasm
                       │   old.txt   │              new.txt               │
                       │   sec/op    │    sec/op     vs base              │
_BaseCase-12             64.43µ ± 3%   62.87µ ± 10%       ~ (p=0.240 n=6)
_ProxyWasmV1_wasmer-12   89.04µ ± 5%   87.58µ ±  1%       ~ (p=0.180 n=6)
_ProxyWasmV1_wazero-12   77.91µ ± 5%   76.21µ ±  2%       ~ (p=0.180 n=6)
geomean                  76.46µ        74.86µ        -2.09%
```

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
this is out of date as latest is 1.2.0

**Comment by spacewander** [comment]
> this is out of date as latest is 1.2.0

@codefromthecrypt 
Will you update this PR or open a new one?

**Comment by codefromthecrypt** [comment]
@spacewander I can update this after https://github.com/mosn/proxy-wasm-go-host/pull/38 merges. thanks for the reminder.

**Comment by codefromthecrypt** [comment]
@spacewander ready

**Review by spacewander — APPROVED** [review]

**Review by doujiang24 — APPROVED** [review]

**Pull request merged**
