### PR TITLE
bugfix: fix some xds convert bugs

### PR DESCRIPTION
**Pull request by kkrrsq**
### Issues associated with this PR

https://github.com/mosn/mosn/issues/2135

### Solutions
bugfix: use defaultConnectRetryTimes when cluster host size is 0
bugfix: istio InboundPassthroughClusterIpv6 infinite loop
bugfix: covert router redirect code error

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by kkrrsq** [comment]
@taoyuanyuan Is there any problem with this PR ? Why not merge ?

**Comment by taoyuanyuan** [comment]
@kkrrsq   I'm sorry my omission, pls @3062 @nejisama  have a look~

**Comment by taoyuanyuan** [comment]
@kkrrsq   I'm sorry my omission, pls @3062 @nejisama  have a look~

**Review by 3062 — APPROVED** [review]
LGTM

**Review by jizhuozhi — APPROVED** [review]
LGTM

**Review by doujiang24 — APPROVED** [review]

**Comment by doujiang24** [comment]
@kkrrsq Thanks for your patch and sorry for the delay!

**Pull request merged**
