### PR TITLE
fix: add interface method

### PR DESCRIPTION
**Pull request by CodingSinger**
Change-Id: I6ddb102183a575c5579f5e9aa30206ac09e2a8f1

### Issues associated with this PR

Your PR should present related issues you want to solve.

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by nejisama** [comment]
pr没改对啊 对应的实现没有加上。。

**Comment by CodingSinger** [comment]
> pr没改对啊 对应的实现没有加上。。

多pick了一个接口，我改了

**Review by nejisama — APPROVED** [review]
LGTM

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Pull request merged**
