### PR TITLE
add xds-server config sample

### PR DESCRIPTION
**Pull request by Bryce-huang**
### Issues associated with this PR

https://github.com/mosn/mosn/issues/2074

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by Bryce-huang** [comment]
> @yzj0911 pls review this.

any change?

**Comment by yzj0911** [comment]
Mosn is not updated after XDS modifies the service  。Are you in this situation ，again？ I am checking this question

**Comment by Bryce-huang** [comment]
> Mosn is not updated after XDS modifies the service 。Are you in this situation ，again？ I am checking this question

It seemed like this before, but now it works for me.

**Review by yzj0911 — APPROVED** [review]
The examples of XDS can run successfully

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Review by nejisama — APPROVED** [review]

**Pull request merged**
