### PR TITLE
Bugfix some issue when close connection

### PR DESCRIPTION
**Pull request by wangfakang**
### Issues associated with this PR

Your PR should present related issues you want to solve.

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by alpha-baby** [comment]
LGTM

**Review by alpha-baby — APPROVED** [review]

**Review by nejisama — APPROVED** [review]

**Comment by taoyuanyuan** [comment]
@wangfakang  需要重新提一个，被revert了

**Comment by MengJiapeng** [comment]
@taoyuanyuan 我们也遇到了k8s readiness 探针导致MOSN频繁刷 reset stream 日志的情况，请问这个PR当时为什么会被revert呢？这个PR的修改能否重新merge到master分支？

**Comment by taoyuanyuan** [comment]
> @taoyuanyuan 我们也遇到了k8s readiness 探针导致MOSN频繁刷 reset stream 日志的情况，请问这个PR当时为什么会被revert呢？这个PR的修改能否重新merge到master分支？

这个修复方案还有一些优化，近期我们再重新提一下 @wangfakang

**Comment by taoyuanyuan** [comment]
> @taoyuanyuan 我们也遇到了k8s readiness 探针导致MOSN频繁刷 reset stream 日志的情况，请问这个PR当时为什么会被revert呢？这个PR的修改能否重新merge到master分支？

@MengJiapeng  pls have a try this PR. https://github.com/mosn/mosn/pull/1956

**Comment by MengJiapeng** [comment]
> > @taoyuanyuan 我们也遇到了k8s readiness 探针导致MOSN频繁刷 reset stream 日志的情况，请问这个PR当时为什么会被revert呢？这个PR的修改能否重新merge到master分支？
> 
> @MengJiapeng pls have a try this PR. #1956

OK, thank you!

**Pull request merged**
