### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by threestoneliu**
Signed-off-by: threestoneliu <threestoneliu@outlook.com>

### Solutions
fix typos

### CODE REVIEW

**Comment by taoyuanyuan** [comment]
already done？

**Comment by threestoneliu** [comment]
I just start reading mosn source code. And I'll doing this work before next week. So I have added wip label in this pr's title.

**Comment by taoyuanyuan** [comment]
good catch ~ 👍

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Review by antJack — APPROVED** [review]
LGTM

**Pull request merged**
