### PR TITLE
ci: the Go version is decided by the image used in the CI

### PR DESCRIPTION
**Pull request by muyuan0**
Previously we didn't test mosn with the expected Go version.
Signed-off-by: muyuan0 <127020730+muyuan0@users.noreply.github.com>

### Issues associated with this PR

Your PR should present related issues you want to solve.

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by doujiang24** [comment]
wow, it found a failure in golang:1.17
```
--------Run test package: mosn.io/mosn/pkg/filter/stream/proxywasm
# github.com/tetratelabs/wazero/internal/descriptor
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:16:16: syntax error: unexpected ~, expecting ]
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:22:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:34:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:56:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:84:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:96:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:107:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:112:4: syntax error: non-declaration statement outside function body
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:120:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:137:15: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-rc.1/internal/descriptor/table.go:137:15: too many errors
note: module requires Go 1.18
FAIL	mosn.io/mosn/pkg/filter/stream/proxywasm [build failed]
```
https://github.com/mosn/mosn/actions/runs/4645088036/jobs/8221049374?pr=2288

@antJack Could you please take a look?

**Comment by muyuan0** [comment]
It seems that wazero uses generics which is not supported by Go 1.17.

**Comment by spacewander** [comment]
Look like we have to drop the support of Go 1.17
Drop wazero in Go 1.17 requires a big refactor and will break API.

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Comment by spacewander** [comment]
https://github.com/mosn/mosn/actions/runs/4707421740/jobs/8350950037

> FAIL	mosn.io/mosn/pkg/mtls/crypto/tls	121.210s

Look like the TLS tests are failed in Go 1.20. Since the 1.20 is tested in the master and it's not relative to what this PR wants to fix, maybe we can track it in the other issue.

**Review by doujiang24 — APPROVED** [review]

**Review by taoyuanyuan — APPROVED** [review]

**Comment by taoyuanyuan** [comment]
@spacewander   modify go version in mosn/pkg and mosn/api also.

**Pull request merged**
