### PR TITLE
Add dubbo sample for mosn proxy

### PR DESCRIPTION
**Pull request by CodingSinger**
Add simple dubbo example for mosn proxy

### CODE REVIEW

**Comment by CodingSinger** [comment]
Can someone tell me why this ci error occurs？

**Comment by rootsongjc** [comment]
Stage 2: Integrate failed. https://travis-ci.com/github/mosn/mosn/jobs/298143953

```
2020-03-14 13:36:01,892 [INFO] mosn start server
--- FAIL: TestTransfer (39.62s)
    server.go:75: server 127.0.0.1:8080 Accept connection: 127.0.0.1:40948
    xprotocol_rpc.go:238: RPC Server receive streamId: 1 
    xprotocol_rpc.go:139: RPC client receive streamId:1 
... omitted ...
    transfer_test.go:127: transfer test failed, error: request get no response
    server.go:88: server 127.0.0.1:8080 closed
FAIL
--- PASS: TestTransfer (40.01s)
PASS
--- PASS: TestTransfer (41.01s)
PASS
--- PASS: TestTransfer (41.02s)
PASS
FAIL	mosn.io/mosn/test/integrate/transfer	64.043s
make: *** [Makefile:40: integrate-local] Error 1
make: *** [integrate] Error 2
The command "make integrate" exited with 2.

**Comment by CodingSinger** [comment]
> Stage 2: Integrate failed. https://travis-ci.com/github/mosn/mosn/jobs/298143953
> 
> ```
> 2020-03-14 13:36:01,892 [INFO] mosn start server
> --- FAIL: TestTransfer (39.62s)
>     server.go:75: server 127.0.0.1:8080 Accept connection: 127.0.0.1:40948
>     xprotocol_rpc.go:238: RPC Server receive streamId: 1 
>     xprotocol_rpc.go:139: RPC client receive streamId:1 
> ... omitted ...
>     transfer_test.go:127: transfer test failed, error: request get no response
>     server.go:88: server 127.0.0.1:8080 closed
> FAIL
> --- PASS: TestTransfer (40.01s)
> PASS
> --- PASS: TestTransfer (41.01s)
> PASS
> --- PASS: TestTransfer (41.02s)
> PASS
> FAIL	mosn.io/mosn/test/integrate/transfer	64.043s
> make: *** [Makefile:40: integrate-local] Error 1
> make: *** [integrate] Error 2
> The command "make integrate" exited with 2.
> ```
I haven't changed this file...

**Comment by nejisama** [comment]
case already passed

**Comment by CodingSinger** [comment]
> case already passed

Thanks for your help, can you help me review？

**Comment by nejisama** [comment]
please add a readme file in  examples/cn_readme or examples/en_readme

**Comment by CodingSinger** [comment]
> please add a readme file in examples/cn_readme or examples/en_readmeok
done~

**Comment by CodingSinger** [comment]
> please add a readme file in examples/cn_readme or examples/en_readme

done

**Pull request merged**
