### PR TITLE
bugfix: unexpected handler of signal interrupt

### PR DESCRIPTION
**Pull request by cuiweixie**
#1906 

Your PR should present related issues you want to solve.

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by doujiang24** [comment]
Nice catch! I think we don't need to catch the `INT` signal in both  `catchSignalsPosix` and `catchSignalsCrossPlatform` since `syscall.SIGINT` eq `os.Interrupt`.

I have fixed it in another big PR in: https://github.com/mosn/mosn/pull/1859/files#diff-ff855c91e9da873e07593105f8123e6b43204398fc199f1d141481c85b8b57cfR73
It will be very helpful if you have time to help review it.

**Comment by cuiweixie** [comment]
press ctrl+c twice the catchSignalsPosix will cause exit forcely without waiting catchSignalsCrossPlatform. at the beginning, I think i could be some posix spec. but it seems not after I google it just now.

**Comment by doujiang24** [comment]
> press ctrl+c twice the catchSignalsPosix will cause exit forcely without waiting catchSignalsCrossPlatform. at the beginning, I think i could be some posix spec. but it seems not after I google it just now.

I think it's just some friendly usage, not necessary. I prefer to make it simpler.

**Comment by doujiang24** [comment]
@cuiweixie Already fixed in https://github.com/mosn/mosn/pull/1859. Thanks, closing it.

**Pull request closed without merging**
