### PR TITLE
feature: support envoy.lb for filter_metadata

### PR DESCRIPTION
**Pull request by striveniu**
### Solutions
添加filter_metadata中对envoy.lb的判断和转换。

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by striveniu** [comment]
> pls add a testcase.



> pls add a testcase.

测试是整体运行起来，后端整合polaris写入规则，前端请求判断运行的。是需要单纯的函数的测试用例么？

**Comment by taoyuanyuan** [comment]
> 
> 
> 
> > pls add a testcase.
> 
> 
> 
> > pls add a testcase.
> 
> 测试是整体运行起来，后端整合polaris写入规则，前端请求判断运行的。是需要单纯的函数的测试用例么？

https://www.github.com/mosn/mosn/tree/master/istio%2Fistio1106%2Fxds%2Fconv%2Fconvert_test.go
可以参考这个哈

**Review by nejisama — DISMISSED** [review]
LGTM

**Comment by nejisama** [comment]
> > pls add a testcase.
> 
> > pls add a testcase.
> 
> 测试是整体运行起来，后端整合polaris写入规则，前端请求判断运行的。是需要单纯的函数的测试用例么？

可以模拟一个有对应结构的pb struct，写单元测试就可以了

**Review by nejisama — COMMENTED** [review]
add unit test later

**Review by nejisama — APPROVED** [review]

**Review by doujiang24 — APPROVED** [review]

**Pull request merged**
