### PR TITLE
Fix flag.Parse for TarsGo.

### PR DESCRIPTION
**Pull request by wangfakang**
### Issues associated with this PR

In order to be compatible with the parameters of the `pilot-agent` when starting the proxy, So sync the fix [PR](https://github.com/TarsCloud/TarsGo/commit/0022231bc5b2b1c148b79af1b24c1b6b9427017f#diff-40fcccf790d9f7def67338159e19c233) of tars library. Now `mosn` can be managed via `pilot-agent` as below:

```
/usr/local/bin/mosn -c /etc/istio/proxy/envoy0.json --restart-epoch 1 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-pilot --service-node sidecar~192.168.5.12~istio-pilot-6654897fc6-vh299.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --log-format [Envoy (Epoch 1)] [%Y-%m-%d %T.%e][%t][%l][%n] %v -l warning --component-log-level misc:error
```

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by zonghaishang** [comment]
`github.com/TarsCloud/TarsGo v0.0.0-20190521041003-0022231bc5b2` @wangfakang 这个库版本你是在哪里看到的？

我在github发布貌似没有发现：https://github.com/TarsCloud/TarsGo/releases

**Comment by wangfakang** [comment]
> `github.com/TarsCloud/TarsGo v0.0.0-20190521041003-0022231bc5b2` @wangfakang 这个库版本你是在哪里看到的？
> 
> 我在github发布貌似没有发现：https://github.com/TarsCloud/TarsGo/releases

sync  [commit](https://github.com/TarsCloud/TarsGo/commit/0022231bc5b2b1c148b79af1b24c1b6b9427017f#diff-40fcccf790d9f7def67338159e19c233).

**Comment by zonghaishang** [comment]
@wangfakang thanks, 最后面试commitId, 前半部分从哪里获取的？ v0.0.0-20190521041003

**Comment by wangfakang** [comment]
> @wangfakang thanks, 最后面看起来是commitId, 前半部分从哪里获取的？ v0.0.0-20190521041003

go get github.com/xxxx/yyyy@${commit_id}

**Comment by zonghaishang** [comment]
thanks, it works.

```
export GO111MODULE=on

➜  ~ go get github.com/TarsCloud/TarsGo@0022231bc5b2b1c148b79af1b24c1b6b9427017f

go: finding github.com/TarsCloud/TarsGo 0022231bc5b2b1c148b79af1b24c1b6b9427017f
go: downloading github.com/TarsCloud/TarsGo v0.0.0-20190521041003-0022231bc5b2
go: extracting github.com/TarsCloud/TarsGo v0.0.0-20190521041003-0022231bc5b2
go: finding github.com/TarsCloud/TarsGo v1.1.2
go: downloading github.com/TarsCloud/TarsGo v1.1.2
go: extracting github.com/TarsCloud/TarsGo v1.1.2
```

**Comment by zonghaishang** [comment]
`mosn:feature-istio_adapter `:  When do you merge into the master branch?

**Pull request merged**
