### PR TITLE
引用的buffer.ConnReadTimeout 变更为 types.DefaultConnReadTimeout

### PR DESCRIPTION
**Pull request by fibbery**
### Issues associated with this PR
#2050 

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by taoyuanyuan** [comment]
pls fix testcae also.

**Comment by taoyuanyuan** [comment]
TestIdleChecker 只改了一半，测试挂了，建议批量替换一把

**Comment by taoyuanyuan** [comment]
> > 
> 
> buffer.ConnReadTimeout是var类型，用例里面从15s�改成了1s� 但是要替换的types.DefaultConnReadTimeout是const�，不能做变更。 只能让这个测试用例的执行时间变长了

哦，结果是个const，要不都改成var，不然看测试用例都挂了

**Comment by fibbery** [comment]
> 

我处理一些， 那几个const的确不利于测试。。

**Comment by taoyuanyuan** [comment]
TestIdleTimeoutAndUpdate 这个没修改，挂了·

**Comment by fibbery** [comment]
> TestIdleTimeoutAndUpdate 这个没修改，挂了~

原来有私自定义var refrence const的，我变更了const之后没注意，已经修改了

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Review by nejisama — APPROVED** [review]

**Pull request merged**
