### PR TITLE
Fix spelling error for `matcher` #2069

### LINKED ISSUE #2069: There are many `matcher` spelling errors in the code
### Describe the bug

There are many `matcher` spelling errors in the code.

### Actual behavior
`macther` in code.

### PR DESCRIPTION
**Pull request by chenzhiguo**
### Issues associated with this PR

Fix #2069

### Solutions
Fix spelling error

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Review by taoyuanyuan — APPROVED** [review]
thank you～ LGTM

**Comment by taoyuanyuan** [comment]
cc @zonghaishang @YIDWang

**Review by YIDWang — APPROVED** [review]
LGTM

**Review by antJack — APPROVED** [review]
LGTM

**Pull request merged**
