### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by threestoneliu**
Signed-off-by: threestoneliu <threestoneliu@outlook.com>

### Solutions
fix typo

### CODE REVIEW

**Comment by taoyuanyuan** [comment]
pls sign cla
http://cla.sofastack.tech/mosn

**Comment by threestoneliu** [comment]
> 



> pls sign cla http://cla.sofastack.tech/mosn

done

**Comment by taoyuanyuan** [comment]
thank you for your contribution~

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Review by doujiang24 — APPROVED** [review]

**Pull request merged**
