### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by yannsun**
### Issues associated with this PR

Your PR should present related issues you want to solve.

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by taoyuanyuan** [comment]
@yannsun  Please sign CLA, thanks for your contribution.

**Comment by nejisama** [comment]
please sign the cla

**Comment by yannsun** [comment]
> please sign the cla

I have signed cla，can you check my cla status。
infoflow 2021-09-23 13-52-58

**Comment by yannsun** [comment]
@taoyuanyuan @nejisama hello, I have signed cla，don't know why can't pass cla bot-check😂

**Comment by taoyuanyuan** [comment]
It‘s ok now, maybe have some bugs. -_-||
thanks

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Review by antJack — APPROVED** [review]
LGTM

**Pull request merged**
